version: '3.3'

services:

  application:
    image:
      application-image
    container_name: application
    networks:
      - cloud
    ports:
      - 80:8080
    depends_on:
      - database
      - redis
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/app_db"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=abc123"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6380"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image:
      postgres
    container_name: postgresql-container
    networks:
      - cloud
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
    volumes:
      - pgdata:/var/lib/postgres/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  redis:
    image:
      redis-image
    container_name:
      redis_db
    networks:
      - cloud
    ports:
      - 6380:6380
    volumes:
      - redis-volume:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"


volumes:
  redis-volume:
    external: true
  pgdata:
    external: true

networks:
  cloud:
    external: true
